### ISSUE TITLE
Error: The getter 'this' isn't defined for the class 'AnsiColor'

### ISSUE THREAD

**Issue by EdwynZN** [Bungeefan/logger#1]
https://github.com/Bungeefan/logger/blob/bf2c13c30fdd9f8752748d938d23a6b81c5bcc31/lib/src/ansi_color.dart#L39

Even if the lint says you shouldn't wrap a single word with `{}`, `this` cannot be interpolated without it 

`Dart SDK version: 2.18.6`

Bump to use at least Dart SDK 2.19 in pubspec

**Comment by Bungeefan** [comment]
Thanks for reporting this!
I guess it would be better to use `${this}` again instead of bumping the min. SDK.
