### ISSUE TITLE
StackTraceBeginIndex not working as expected

### ISSUE THREAD

**Issue by TrifiAmanallah** [Bungeefan/logger#14]
Setting stackTraceBeginIndex to 1 or 2, dosn't  seem to have an effect.
Expected result: First line in stack trace should be skipped

Refer to th following issues from old repo:
[stackTraceBeginIndex not working as expected (fixes #114) ](https://github.com/simc/logger/pull/142)
[stackTraceBeginIndex: 1 vs 0 or 2 appears to have no effect #114](https://github.com/simc/logger/issues/114)

**Comment by Bungeefan** [comment]
This was already addressed in f7f4779f77ed698de455cadcd008cf9f85d40b6a, this commit just isn't yet on pub.dev.
Please try again when this version is being published on pub.dev or via the GitHub link.

If you still think there is something wrong, feel free to ping me to re-open this issue or create a new issue.
