### ISSUE TITLE
Run handlers without showing the log

### ISSUE THREAD

**Issue by diegocatalao** [Bungeefan/logger#24]
Hello, Folks.

In some cases it would be interesting to run the registered handlers even without needing to show the log. [This line](https://github.com/Bungeefan/logger/blob/2a047d4cd6fd25679ca0471dd49256f26b0a9743/lib/src/logger.dart#L122) block all handlers execution.

Would it be possible to make a change in this regard?

Tanks!

**Comment by Bungeefan** [comment]
@diegocatalao
I would like to keep this open, so that it actually gets done.
Or is this now obsolete?

**Comment by diegocatalao** [comment]
@Bungeefan My bad. I ended up accidentally closing 😅
