### ISSUE TITLE
Error while using this package. 

### ISSUE THREAD

**Issue by iRawNewton** [Bungeefan/logger#28]
This is the error log
──────
I/flutter ( 6257): │ #0   _MyHomePageState._incrementCounter (package:flutter_design/main.dart:46:12)
main.dart:46
I/flutter ( 6257): │ #1   _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1096:21)
ink_well.dart:1096
I/flutter ( 6257): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄

**Comment by Bungeefan** [comment]
Hi, based on your provided information, I don't see any indications that this has something to do with the logger package.
Additionally, please try to provide a reproducible code sample, otherwise we are unable to do anything.
