### ISSUE TITLE
Investigate adoption of dart's developer `log` signature

### ISSUE THREAD

**Issue by Bungeefan** [Bungeefan/logger#29]
Adopting the same (or similar) signature as `dart:developer.log` would have several benefits:
* Making it easier to migrate to this package.
* No need to provide `null` for the error object to provide a stack trace.
* Would allow additions of more optional features like the one in #11.

Feel free to add your comments and ideas to this issue!

**Comment by kulame** [comment]
i also need tag optional

**Comment by Bungeefan** [comment]
@kulame Please vote for it in its [respective issue](https://github.com/Bungeefan/logger/issues/11) by adding a :+1: to the initial post.
This issue is about the new signature that was adopted.
