### ISSUE TITLE
Getting LogOutput not found issue

### ISSUE THREAD

**Issue by singhtaranjeet** [Bungeefan/logger#3]
![logger issue](https://user-images.githubusercontent.com/22328750/220864020-eba085f2-41f7-4e74-8843-0fb81326c426.jpeg)
Working fine in 1.1.0 but in the latest version after extending the LogOutput getting this issue.

**Comment by ChristopheOosterlynck** [comment]
I had the same issue and proposed a fix: https://github.com/Bungeefan/logger/pull/4

2 workarounds:
* stay on 1.1.0 :)
* include logger/src/log_output.dart directly where needed

**Comment by Bungeefan** [comment]
Thanks for reporting this!
`1.2.2` should fix this.
