### ISSUE TITLE
Add web compatibility?

### ISSUE THREAD

**Issue by cbarlow26** [Bungeefan/logger#30]
Any plans on making this package compatible with the web platform? According to [Pana](https://pub.dev/packages/pana) analysis, it's not compatible because it imports `dart:io`.

**Package not compatible with platform Web**

Because:
* `package:logger/logger.dart` that imports:
* `package:logger/src/outputs/file_output_stub.dart` that imports:
* `dart:io`

**Comment by Bungeefan** [comment]
Hi, this is just an analyzing issue as it is a conditional import and will only be imported on a platform that supports `dart:io`.
If you still have problems using it in the web, feel free to reopen.

**Comment by cbarlow26** [comment]
Ok, will do, thanks!
