### ISSUE TITLE
v2 log signature changed

### ISSUE THREAD

**Issue by hampsterx** [Bungeefan/logger#39]
note for those about to get hit by this, esp if your CI server makes test fails not obvious the actual error, doh

I was/am using like so

     log.w(err, "some msg");

You have just published new version, I need to upgrade I guess...
 
 And for now I pin to v1 doh 
     
```
  # log signature changed in 2.x
  logger: ^1.4.0
  ```
  
  Would recommend update readme to show usage of additional args tho
  
  Documentation
Log level
You can log with different levels:

logger.t("Trace log");

logger.d("Debug log");

logger.i("Info log");

logger.w("Warning log");

logger.e("Error log");

logger.f("What a fatal log");

---

right, named args ok..

```
d(dynamic message, {DateTime? time, Object? error, StackTrace? stackTrace}) → void
Log a message at level Level.debug.
```

**Comment by Bungeefan** [comment]
Hi, yeah, sorry the README slipped my update.
Going to update it asap.

**Comment by Bungeefan** [comment]
9706885
