### ISSUE TITLE
weird behaviour while using logger with workmanager

### ISSUE THREAD

**Issue by milindgoel15** [Bungeefan/logger#42]
Hi,

I wanted to log a message based on the result of the work manager job in my app. So on success run, it shows ran successfully or error in case of failure run. So I checked in the case of success run and this is what i got in the logs:

<details>
<summary>console logs</summary>

```console
I/flutter (10449): │ #0   callbackDispatcher.<anonymous closure> (package:weatherwise/main.dart:97:18)
main.dart:97
I/flutter (10449): │ #1   <asynchronous suspension>
I/flutter (10449): │ 💡 Scheduled job ran successfully!
```

</details>

it throw some exception of some kind?

This is my work manager code with logger:

<details>
<summary>code</summary>

```dart
  Workmanager().executeTask((task, inputData) async {
    switch (task) {
      case "currentWeather":
        final sharedPreference = await SharedPreferences.getInstance();

        try {
          final weatherResponse = await WidgetService()
              .getWidgetWeather(sharedPreference.getString('activeKey') ?? "");

          WidgetService().updateWidget(weatherResponse);
          logger.i("Scheduled job ran successfully!");
        } catch (e) {
          logger.e(
            'Error occurred while fetching weather:',
            error: e,
          );
        }

        return Future.value(true);
    }
    return Future.value(true);
  });
```

</details>

**Comment by Bungeefan** [comment]
Hi, I figured that you didn't configure a custom printer and are therefore using the default printer (`PrettyPrinter`) for the logger.

`PrettyPrinter` has by default a `methodCount` of `2`, which means that every log, **even non errors**, is accommodated by a stack trace.

You can disable that feature by providing your own printer instance with a `methodCount` of `0`:
```dart
var logger = Logger(
  printer: PrettyPrinter(methodCount: 0),
);
```

**Comment by milindgoel15** [comment]
Oh, thats why. 

Also, can we disable the rectangle border as well?

**Comment by Bungeefan** [comment]
Sure, just set `noBoxingByDefault: true`.
