### ISSUE TITLE
Can't see file path on VSCode Debug Console

### ISSUE THREAD

**Issue by MaldonadoAndres** [Bungeefan/logger#49]
What I mean is the small link to the file from where the log was Output
![Captura de pantalla 2023-12-04 a la(s) 4 29 26 p  m](https://github.com/SourceHorizon/logger/assets/42980462/aacfe931-5bfd-4afc-b7f5-213f1be1bdae)
![Captura de pantalla 2023-12-04 a la(s) 4 30 45 p  m](https://github.com/SourceHorizon/logger/assets/42980462/368be052-b8b3-42f9-a7d3-add2ff09bc5a)

**Comment by MaldonadoAndres** [comment]
@Bungeefan I just wanted to thank you for redirecting me to this issue I found the solution there

**Comment by Darecjo** [comment]
@Bungeefan Could you please explain the solution you found ?
