### ISSUE TITLE
[PrettyPrinter] Stack Trace: Use `errorMethodCount` only if an error was provided

### ISSUE THREAD

**Issue by Bungeefan** [Bungeefan/logger#6]
I am creating this issue to pick up this pull request: https://github.com/simc/logger/pull/139

### Summary
**PrettyPrinter** should use `errorMethodCount` for Stack Traces only if an `error` was provided, otherwise it should use `methodCount`.

### Voting
Please add the :+1: reaction, if you would like to see this implemented.

**Comment by cedvdb** [comment]
hum error level should use errorMethodCount tbh

**Comment by icodeyou** [comment]
I agree, I think it's weird that when you use both parameters : 
```
         methodCount: 0,
         errorMethodCount: 10,
```

It looks like methodCount "overrides" errorMethodCount.

With this code, I don't see any stacktrace for my error logs, but I would like to see them.
