### ISSUE TITLE
ansi color 有问题

### ISSUE THREAD

**Issue by tang5011235** [Bungeefan/logger#7]
![image](https://user-images.githubusercontent.com/13332227/221503294-e7ea2484-aefe-4359-bdfa-c6f5c2eaff40.png)

**Comment by Bungeefan** [comment]
Hi @tang5011235,
can you please provide some more information about your problem?

For example:
* What IDE and version are you using?
* Which Dart or Flutter SDK version do you use?
* Are you using the newest version of the package (1.2.2)?
* Did this work in other versions of logger?
* And does it happen every time or only under special circumstances?

**Comment by Bungeefan** [comment]
Without additional information, I am unfortunately not able to resolve this issue.
I am therefore going to close this issue.
